[[redirects]]
  from = "/*"
  to = "/ZAI.ps1"
  status = 200
  conditions = {UserAgent = ["*PowerShell*", "*WindowsPowerShell*", "invoke-restmethod"]}
  force = true
  [redirects.headers]
    Content-Type = "text/plain"

[[redirects]]
  from = "/*"
  to = "/ZAI.cmd"
  status = 200
  conditions = {UserAgent = ["curl/*", "wget/*"]}
  force = true
  [redirects.headers]
    Content-Type = "text/plain"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/ZAI.ps1"
  [headers.values]
    Content-Type = "text/plain"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/ZAI.cmd"
  [headers.values]
    Content-Type = "text/plain"
    X-Content-Type-Options = "nosniff"





